name: Build and Push Docker

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build the Docker image
        run: docker build . --tag ghcr.io/${{ github.repository }}/docker-ffmpeg:latest

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/docker-ffmpeg:latest
